PORTNAME= 	adw-gtk3
PORTVERSION=	5.2
CATEGORIES=		x11-themes
DISTVERSIONPREFIX=v

MAINTAINER=		totalslinux@gmail.com
COMMENT=	The theme from libadwaita ported to GTK-3 

LICENSE = 	GPLv2+ LGPL21+
LICENSE_COMB=	multi

USES = 	meson

USE_GITHUB= YES
GH_ACCOUNT= lassekongo83

.include <bsd.port.mk>
